<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');

$lang = explode('-', $this->lang())[0];

$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

if (isset($itemSet)):
    $this->htmlElement('body')->appendAttribute('class', 'item-set show');
endif;

$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>

<?php if (isset($itemSet)): ?>
    <div class="show-header">
    <?php echo $this->pageTitle($itemSet->displayTitle(null, $lang), 2); ?>
    <h3><?php echo $translate('Item Set'); ?></h3>
    </div>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <?php echo $this->pageTitle($translate('Items'), 3); ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>
<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <li class="item resource">
        <?php echo $this->partial('common/helper/item-thumbnail', [ 'resource' => $item ]); ?>
        <h4><?php echo $item->link($item->displayTitle(null, $lang)); ?></h4>
        <?php if ($date = $item->value('dcterms:date')): ?>
        <div class="date"><?php echo $date; ?></div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>


