<?php

if ($resource) {
    $medium = $resource->thumbnailDisplayUrl('medium');
    $large = $resource->thumbnailDisplayUrl('large');
    
    if ($medium && $large) {
        if ($medium == $large) {
            $thumbnail = $this->thumbnail($resource, 'medium');
        } else {
            $thumbnail = $this->thumbnail($resource, 'medium', [
                'srcset' => $medium . ' 200w, ' . $large . ' 800w',
                'sizes' => '(max-width: 640px) 50vw, 25vw' ]);
        }
        echo $resource->linkRaw($thumbnail);
    }
}

?>